# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 216d3f02955eaeea7603d71f449dce48f614d1f2ee33057120ce474e43721621a8f2210ebc5a55721d24d7551f79c2665bf22c1ab72f8c1765696d9b18f5ed63

test:
  secret_key_base: ef2f8da5efcf96bcf28645a42e3ad9e2f1f6cea5f482ba6ecbc082e8dd6b0f6282c2b98ed82b73e2825c70bacf9b5b16b5b9f907a33daca94bafe7632bb57f79

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
